### ISSUE TITLE
Invalid version error

### ISSUE THREAD

**Issue by philwinder** [inetprocess/gitlab-release#2]
Hey, useful project, thanks.

I'm getting an error when using the docker container. This is from within gitlab:

```
$ gitlab-release --message 'See [the readme file](README.md) for documentation.' some-file-$CI_BUILD_TAG
Traceback (most recent call last):
  File "/usr/bin/gitlab-release", line 149, in <module>
    release = GitlabRelease(args.debug)
  File "/usr/bin/gitlab-release", line 17, in __init__
    self.api_project_url = self.get_api_project_url()
  File "/usr/bin/gitlab-release", line 50, in get_api_project_url
    if self.is_gitlab_v9():
  File "/usr/bin/gitlab-release", line 30, in is_gitlab_v9
    return StrictVersion(gl_version) >= StrictVersion('9.0.0')
  File "/usr/local/lib/python3.6/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.6/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '9.5.0-rc2-ee'
```

It seems to be failing when checking the version number. It looks like `9.5.0-rc2-ee` can't be parsed properly. Maybe strip everything after the first three numbers?

**Comment by remisauvat** [comment]
Thanks for the report.

I have updated the code to use LooseVersion comparison which should not have problem parsing any exotic version string.

You can pull the new docker image.
